"""Clean MobileNetV3-Small full-leaf cGAN configuration."""

import os
from config_cgan import *

FULL_IMAGE_SIZE = int(os.getenv("PIX2SPECTRAL_FULL_IMAGE_SIZE", 220))
RETURN_STAGE_INDEX = True
CACHE_FULL_IMAGES = bool(int(os.getenv("PIX2SPECTRAL_CACHE_FULL_IMAGES", "0")))

# External preprocessing should provide resized/padded/normalized images.
IMAGE_NORMALIZATION_SCOPE = "none"
IMAGE_NORMALIZATION_METHOD = "none"
NORMALIZATION_STATS_PATH = None
RECOMPUTE_NORMALIZATION_STATS = False

USE_MOBILENETV3_FULLLEAF = True
MOBILENET_PRETRAINED = bool(int(os.getenv("PIX2SPECTRAL_MOBILENET_PRETRAINED", "1")))
MOBILENET_FREEZE_ALL_EXCEPT_LAST = False
MOBILENET_TOKEN_DIM = int(os.getenv("PIX2SPECTRAL_MOBILENET_TOKEN_DIM", 64))
MOBILENET_ATTENTION_LAYERS = int(
    os.getenv("PIX2SPECTRAL_MOBILENET_ATTENTION_LAYERS", 1)
)
MOBILENET_ATTENTION_HEADS = int(os.getenv("PIX2SPECTRAL_MOBILENET_ATTENTION_HEADS", 2))
MOBILENET_DROPOUT = float(os.getenv("PIX2SPECTRAL_MOBILENET_DROPOUT", 0.35))
MOBILENET_ADAPTER_HIDDEN_CHANNELS = int(
    os.getenv("PIX2SPECTRAL_MOBILENET_ADAPTER_HIDDEN_CHANNELS", 8)
)

USE_STAGE_AUXILIARY_LOSS = True
STAGE_AUX_WEIGHT = float(os.getenv("PIX2SPECTRAL_STAGE_AUX_WEIGHT", 0.05))
NUM_STAGE_CLASSES = 5
USE_STAGE_AS_CONDITION = False

USE_CONDITIONAL_DISCRIMINATOR = True
USE_MISMATCHED_CONDITION_LOSS = False
LAMBDA_MISMATCH = float(os.getenv("PIX2SPECTRAL_LAMBDA_MISMATCH", 0.0))
DISCRIMINATOR_MODE = "segmented"
USE_SEGMENTED_PROSPECT = True
USE_SEGMENT_RESIDUAL = True

BATCH_SIZE = int(os.getenv("PIX2SPECTRAL_BATCH_SIZE", 2))
NUM_WORKERS = int(os.getenv("PIX2SPECTRAL_NUM_WORKERS", 0))
PERSISTENT_WORKERS = False
LEARNING_RATE = float(os.getenv("PIX2SPECTRAL_LEARNING_RATE", 2e-5))
BEST_MODEL_METRIC = os.getenv("PIX2SPECTRAL_BEST_MODEL_METRIC", "val_l1")
BEST_MODEL_MODE = os.getenv("PIX2SPECTRAL_BEST_MODEL_MODE", "min")
