"""
Improved generator model for pix2spectral.

Main additions relative to the original generator_model.py:
  - optional segmented PROSPECT-D generation over configurable wavelength ranges
  - optional small learned residual spectrum to capture shapes not generated by PROSPECT-D
  - wavelength-grid and spectral-segment utilities
  - faster CNN patch encoder option
  - GroupNorm/InstanceNorm/BatchNorm factory instead of BatchNorm-only blocks
  - attention + statistics pooling over leaf patches
  - optional shared or separate band encoders
  - vectorized forward_batch_list over variable patch counts per sample/band

Scientific note:
  In segmented mode, the model predicts one PROSPECT-D parameter vector per
  spectral segment. These segment-wise parameters are useful as physics-guided
  latent variables, but they should not be interpreted as one physically valid
  whole-leaf PROSPECT-D parameter set.
"""

from __future__ import annotations

from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from pyPro4Sail import prospect_jacobian


DEFAULT_BANDS = ["blue", "green", "red", "nir", "red_edge"]
DEFAULT_SPECTRAL_SEGMENTS = [
    (400.0, 900.0),
    (900.0, 1000.0),
    (1000.0, 2000.0),
    (2000.0, 2500.0),
]


# ============================================================
# Wavelength and segment utilities
# ============================================================


def make_wavelengths_from_values(
    wavelength_min: float = 400.0,
    wavelength_max: float = 2500.0,
    wavelength_count: int = 2101,
) -> np.ndarray:
    """Create a wavelength grid in nanometers."""
    return np.linspace(
        float(wavelength_min),
        float(wavelength_max),
        int(wavelength_count),
        dtype=np.float64,
    )


def normalize_segments(
    spectral_segments: Optional[Sequence[Tuple[float, float]]],
    wavelength_min: float,
    wavelength_max: float,
) -> List[Tuple[float, float]]:
    """Validate spectral segments and return a normalized list."""
    if spectral_segments is None:
        spectral_segments = [(float(wavelength_min), float(wavelength_max))]

    out: List[Tuple[float, float]] = []
    for lo, hi in spectral_segments:
        lo = float(lo)
        hi = float(hi)
        if hi <= lo:
            raise ValueError(f"Invalid spectral segment ({lo}, {hi}). hi must be > lo.")
        if lo < wavelength_min or hi > wavelength_max:
            raise ValueError(
                f"Segment ({lo}, {hi}) is outside wavelength range "
                f"[{wavelength_min}, {wavelength_max}]."
            )
        out.append((lo, hi))

    # Require sorted, non-overlapping, contiguous or near-contiguous segments.
    out = sorted(out, key=lambda x: x[0])
    for i in range(1, len(out)):
        if out[i][0] < out[i - 1][1]:
            raise ValueError(f"Overlapping spectral segments: {out[i - 1]} and {out[i]}.")

    return out


def spectral_segment_indices(
    wavelengths: np.ndarray,
    spectral_segments: Sequence[Tuple[float, float]],
) -> List[np.ndarray]:
    """
    Convert wavelength intervals to index arrays.

    Intervals are half-open [lo, hi) except the last segment, which is
    inclusive [lo, hi]. This avoids duplicate wavelengths at shared boundaries.

    For default 400:2500 with 2101 wavelengths and segments:
      [400,900), [900,1000), [1000,2000), [2000,2500]
    lengths are:
      500, 100, 1000, 501 -> total 2101.
    """
    wavelengths = np.asarray(wavelengths, dtype=np.float64)
    indices: List[np.ndarray] = []

    for i, (lo, hi) in enumerate(spectral_segments):
        if i == len(spectral_segments) - 1:
            mask = (wavelengths >= lo) & (wavelengths <= hi)
        else:
            mask = (wavelengths >= lo) & (wavelengths < hi)

        idx = np.where(mask)[0].astype(np.int64)
        if idx.size == 0:
            raise ValueError(f"Segment ({lo}, {hi}) produced zero wavelength indices.")
        indices.append(idx)

    all_idx = np.concatenate(indices, axis=0)
    if len(np.unique(all_idx)) != len(all_idx):
        raise ValueError("Spectral segments produced duplicate wavelength indices.")

    if all_idx.min() < 0 or all_idx.max() >= wavelengths.size:
        raise ValueError("Spectral segment indices are outside wavelength grid.")

    return indices


def boundary_indices_from_segments(
    wavelengths: np.ndarray,
    spectral_segments: Sequence[Tuple[float, float]],
) -> List[int]:
    """Return integer indices at internal segment boundaries for continuity loss."""
    wavelengths = np.asarray(wavelengths, dtype=np.float64)
    boundaries = []
    for _, hi in spectral_segments[:-1]:
        idx = int(np.argmin(np.abs(wavelengths - float(hi))))
        if 0 < idx < len(wavelengths):
            boundaries.append(idx)
    return boundaries


# ============================================================
# Normalization factories
# ============================================================


def _best_group_count(num_channels: int, max_groups: int = 8) -> int:
    """Largest group count <= max_groups that divides num_channels."""
    max_groups = min(int(max_groups), int(num_channels))
    for g in range(max_groups, 0, -1):
        if num_channels % g == 0:
            return g
    return 1


def norm2d(num_channels: int, norm_type: str = "group") -> nn.Module:
    norm_type = str(norm_type).lower()
    if norm_type in ["group", "gn", "groupnorm"]:
        return nn.GroupNorm(_best_group_count(num_channels), num_channels)
    if norm_type in ["batch", "bn", "batchnorm"]:
        return nn.BatchNorm2d(num_channels)
    if norm_type in ["instance", "in", "instancenorm"]:
        return nn.InstanceNorm2d(num_channels, affine=True)
    if norm_type in ["none", "identity", ""]:
        return nn.Identity()
    raise ValueError(f"Unknown norm_type={norm_type}")


def maybe_spectral_norm(module: nn.Module, enabled: bool = False) -> nn.Module:
    if enabled:
        return nn.utils.spectral_norm(module)
    return module


# ============================================================
# PROSPECT-D parameter bounding and differentiable layer
# ============================================================


class ProspectDParameterBounds(nn.Module):
    """
    Maps raw network outputs to bounded PROSPECT-D parameters with sigmoid scaling.

    Order: (Nleaf, Cab, Car, Cbrown, Cw, Cm, Ant)
    """

    def __init__(self, mins=None, maxs=None, eps: float = 1e-6):
        super().__init__()
        self.eps = float(eps)

        default_mins = torch.tensor(
            [1.0, 0.0, 0.0, 0.0, 0.0001, 0.0001, 0.0], dtype=torch.float32
        )
        default_maxs = torch.tensor(
            [100.0, 1500.0, 100.0, 100.0, 1.0, 1.0, 30.0], dtype=torch.float32
        )

        if mins is None:
            mins = default_mins
        if maxs is None:
            maxs = default_maxs

        mins = torch.as_tensor(mins, dtype=torch.float32)
        maxs = torch.as_tensor(maxs, dtype=torch.float32)

        if mins.shape != (7,) or maxs.shape != (7,):
            raise ValueError("mins and maxs must be shape [7]")
        if torch.any(maxs <= mins):
            raise ValueError("Each max must be > min")

        self.register_buffer("mins", mins)
        self.register_buffer("maxs", maxs)

    def forward(self, raw_params: torch.Tensor) -> torch.Tensor:
        u = torch.sigmoid(raw_params)
        u = u * (1.0 - 2.0 * self.eps) + self.eps
        return self.mins + u * (self.maxs - self.mins)


class ProspectDLayerAnalytic(torch.autograd.Function):
    @staticmethod
    def forward(ctx, params):
        """
        params: torch [B, 7]
        returns: reflectance rho torch [B, L]
        """
        if params.dim() != 2 or params.shape[1] != 7:
            raise ValueError(f"params must be [B,7], got {tuple(params.shape)}")

        if not torch.isfinite(params).all():
            raise FloatingPointError("Non-finite PROSPECT parameters entering forward.")

        p_np = params.detach().cpu().numpy().astype(np.float64)
        B = p_np.shape[0]

        rho_list = []
        J_list = []

        for i in range(B):
            p = p_np[i]

            wl, rho, tau, Delta_rho, Delta_tau = prospect_jacobian.JacProspectD(
                float(p[0]),
                float(p[1]),
                float(p[2]),
                float(p[3]),
                float(p[4]),
                float(p[5]),
                float(p[6]),
            )

            rho = np.asarray(rho, dtype=np.float32).reshape(-1)
            Delta_rho = np.asarray(Delta_rho, dtype=np.float32)

            if not np.isfinite(rho).all():
                raise FloatingPointError(f"Non-finite PROSPECT reflectance at item {i}.")
            if not np.isfinite(Delta_rho).all():
                raise FloatingPointError(f"Non-finite PROSPECT Jacobian at item {i}.")

            if Delta_rho.ndim != 2:
                raise ValueError("Delta_rho must be 2D, got " + str(Delta_rho.shape))

            if Delta_rho.shape[0] == 7:
                J = Delta_rho.T
            elif Delta_rho.shape[1] == 7:
                J = Delta_rho
            else:
                raise ValueError("Unexpected Delta_rho shape: " + str(Delta_rho.shape))

            rho_list.append(rho)
            J_list.append(J)

        rho_np = np.stack(rho_list, axis=0)
        J_np = np.stack(J_list, axis=0)

        ctx.save_for_backward(torch.from_numpy(J_np))
        return torch.from_numpy(rho_np).to(params.device).type_as(params)

    @staticmethod
    def backward(ctx, grad_output):
        (J_t,) = ctx.saved_tensors
        J_t = J_t.to(grad_output.device).type_as(grad_output)
        grad_params = torch.einsum("bl,blk->bk", grad_output, J_t)
        return grad_params


def prospectd_reflectance_torch(params: torch.Tensor) -> torch.Tensor:
    return ProspectDLayerAnalytic.apply(params)


class PhysicsInformedProspectHead(nn.Module):
    """
    raw_params [B, 7] -> bounded pParams [B, 7] -> y_fake [B, L]
    """

    def __init__(self, mins=None, maxs=None):
        super().__init__()
        self.bounds = ProspectDParameterBounds(mins=mins, maxs=maxs)

    def forward(self, raw_params: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        p_params = self.bounds(raw_params)
        y_fake = prospectd_reflectance_torch(p_params)
        return y_fake, p_params


# ============================================================
# Patch encoders
# ============================================================


class ConvBlock2D(nn.Module):
    def __init__(
        self,
        in_ch: int,
        out_ch: int,
        kernel_size: int = 3,
        stride: int = 1,
        norm_type: str = "group",
        activation: str = "leaky",
    ):
        super().__init__()
        padding = kernel_size // 2
        layers: List[nn.Module] = [
            nn.Conv2d(
                in_ch,
                out_ch,
                kernel_size=kernel_size,
                stride=stride,
                padding=padding,
                padding_mode="reflect",
                bias=False,
            ),
            norm2d(out_ch, norm_type),
        ]
        if activation == "leaky":
            layers.append(nn.LeakyReLU(0.2, inplace=True))
        elif activation == "relu":
            layers.append(nn.ReLU(inplace=True))
        else:
            raise ValueError(f"Unknown activation={activation}")
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class PatchCNNEncoder(nn.Module):
    """
    Faster CNN patch encoder.

    Input:
        [N, 1, H, W], typically [N, 1, 32, 32]
    Output:
        [N, embed_dim]

    Unlike the previous U-Net-like encoder, this does not upsample back to the
    original resolution because the task only needs patch embeddings.
    """

    def __init__(
        self,
        in_channels: int = 1,
        base_features: int = 16,
        embed_dim: int = 64,
        norm_type: str = "group",
    ):
        super().__init__()
        f = int(base_features)

        self.net = nn.Sequential(
            ConvBlock2D(in_channels, f, kernel_size=3, stride=1, norm_type=norm_type),
            ConvBlock2D(f, f * 2, kernel_size=4, stride=2, norm_type=norm_type),
            ConvBlock2D(f * 2, f * 4, kernel_size=4, stride=2, norm_type=norm_type),
            ConvBlock2D(f * 4, f * 8, kernel_size=4, stride=2, norm_type=norm_type),
            ConvBlock2D(f * 8, f * 8, kernel_size=4, stride=2, norm_type=norm_type),
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
        )

        self.proj = nn.Sequential(
            nn.Linear(f * 8, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.proj(self.net(x))


class Down(nn.Module):
    def __init__(self, in_ch: int, out_ch: int, norm_type: str = "group"):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(
                in_ch,
                out_ch,
                kernel_size=4,
                stride=2,
                padding=1,
                padding_mode="reflect",
                bias=False,
            ),
            norm2d(out_ch, norm_type),
            nn.LeakyReLU(0.2, inplace=True),
        )

    def forward(self, x):
        return self.net(x)


class Up(nn.Module):
    def __init__(
        self,
        in_ch: int,
        out_ch: int,
        norm_type: str = "group",
        use_dropout: bool = False,
    ):
        super().__init__()
        layers: List[nn.Module] = [
            nn.ConvTranspose2d(
                in_ch, out_ch, kernel_size=4, stride=2, padding=1, bias=False
            ),
            norm2d(out_ch, norm_type),
            nn.ReLU(inplace=True),
        ]
        if use_dropout:
            layers.append(nn.Dropout(0.5))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class SmallUNetPatchEncoder(nn.Module):
    """
    Legacy U-Net style encoder for 32x32 patches.

    Kept for compatibility. The default recommended encoder is PatchCNNEncoder.
    """

    def __init__(
        self,
        in_channels: int = 1,
        base_features: int = 8,
        embed_dim: int = 64,
        norm_type: str = "group",
    ):
        super().__init__()
        f = int(base_features)

        self.initial = nn.Sequential(
            nn.Conv2d(
                in_channels,
                f,
                kernel_size=3,
                stride=1,
                padding=1,
                padding_mode="reflect",
                bias=False,
            ),
            norm2d(f, norm_type),
            nn.LeakyReLU(0.2, inplace=True),
        )

        self.d1 = Down(f, f * 2, norm_type=norm_type)
        self.d2 = Down(f * 2, f * 4, norm_type=norm_type)
        self.d3 = Down(f * 4, f * 8, norm_type=norm_type)
        self.d4 = Down(f * 8, f * 8, norm_type=norm_type)
        self.d5 = Down(f * 8, f * 8, norm_type=norm_type)

        self.u1 = Up(f * 8, f * 8, norm_type=norm_type)
        self.u2 = Up(f * 8 + f * 8, f * 8, norm_type=norm_type)
        self.u3 = Up(f * 8 + f * 8, f * 4, norm_type=norm_type)
        self.u4 = Up(f * 4 + f * 4, f * 2, norm_type=norm_type)
        self.u5 = Up(f * 2 + f * 2, f, norm_type=norm_type)

        self.fuse = nn.Sequential(
            nn.Conv2d(
                f + f,
                f,
                kernel_size=3,
                stride=1,
                padding=1,
                padding_mode="reflect",
                bias=False,
            ),
            norm2d(f, norm_type),
            nn.ReLU(inplace=True),
        )

        self.proj = nn.Sequential(
            nn.Linear(f, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        x0 = self.initial(x)
        x1 = self.d1(x0)
        x2 = self.d2(x1)
        x3 = self.d3(x2)
        x4 = self.d4(x3)
        x5 = self.d5(x4)

        y1 = self.u1(x5)
        y2 = self.u2(torch.cat([y1, x4], 1))
        y3 = self.u3(torch.cat([y2, x3], 1))
        y4 = self.u4(torch.cat([y3, x2], 1))
        y5 = self.u5(torch.cat([y4, x1], 1))

        z = self.fuse(torch.cat([y5, x0], 1))
        z = z.mean(dim=(2, 3))
        z = self.proj(z)
        return z


def build_patch_encoder(
    encoder_type: str,
    in_channels: int,
    base_features: int,
    embed_dim: int,
    norm_type: str,
) -> nn.Module:
    encoder_type = str(encoder_type).lower()
    if encoder_type in ["cnn", "fast_cnn", "patch_cnn"]:
        return PatchCNNEncoder(
            in_channels=in_channels,
            base_features=base_features,
            embed_dim=embed_dim,
            norm_type=norm_type,
        )
    if encoder_type in ["unet", "small_unet", "legacy_unet"]:
        return SmallUNetPatchEncoder(
            in_channels=in_channels,
            base_features=base_features,
            embed_dim=embed_dim,
            norm_type=norm_type,
        )
    raise ValueError(f"Unknown patch encoder type: {encoder_type}")


# ============================================================
# Patch pooling
# ============================================================


class MeanPool(nn.Module):
    out_dim: Optional[int] = None

    def forward(self, E: torch.Tensor) -> torch.Tensor:
        if E.numel() == 0:
            return torch.zeros(E.shape[1], device=E.device, dtype=E.dtype)
        return E.mean(dim=0)


class AttentionStatsPool(nn.Module):
    """
    Pool variable patch embeddings into one fixed-size band descriptor.

    Uses:
      - attention-weighted mean
      - standard deviation across patches
      - max across patches

    Then projects [mean, std, max] back to embed_dim.
    """

    def __init__(self, embed_dim: int, hidden_dim: Optional[int] = None):
        super().__init__()
        embed_dim = int(embed_dim)
        if hidden_dim is None:
            hidden_dim = max(16, embed_dim // 2)

        self.attn = nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.Tanh(),
            nn.Linear(hidden_dim, 1),
        )
        self.proj = nn.Sequential(
            nn.Linear(embed_dim * 3, embed_dim),
            nn.LayerNorm(embed_dim),
            nn.ReLU(inplace=True),
        )

    def forward(self, E: torch.Tensor) -> torch.Tensor:
        if E.numel() == 0:
            return torch.zeros(self.proj[0].out_features, device=E.device, dtype=E.dtype)

        if E.shape[0] == 1:
            mean = E[0]
            std = torch.zeros_like(mean)
            maxv = E[0]
        else:
            logits = self.attn(E).squeeze(-1)
            weights = torch.softmax(logits, dim=0).unsqueeze(-1)
            mean = torch.sum(weights * E, dim=0)
            std = torch.std(E, dim=0, unbiased=False)
            maxv = torch.max(E, dim=0).values

        return self.proj(torch.cat([mean, std, maxv], dim=0))


def build_pool(pooling_type: str, embed_dim: int) -> nn.Module:
    pooling_type = str(pooling_type).lower()
    if pooling_type in ["mean", "avg"]:
        return MeanPool()
    if pooling_type in ["attention_stats", "attn_stats", "attention"]:
        return AttentionStatsPool(embed_dim=embed_dim)
    raise ValueError(f"Unknown pooling_type={pooling_type}")


# ============================================================
# Full generator
# ============================================================


class MultiSpectralPatchToProspectGenerator(nn.Module):
    """
    Multispectral patch generator with optional segmented PROSPECT-D heads.

    Input per sample:
        band_patches dict:
            "blue":     Tensor [N_blue, 1, H, W]
            "green":    Tensor [N_green, 1, H, W]
            ...

    Output per sample:
        y_fake:
            Tensor [L]

        pParams:
            Tensor [7] in full-spectrum mode
            Tensor [num_segments, 7] in segmented mode
    """

    def __init__(
        self,
        bands: Optional[Sequence[str]] = None,
        base_features: int = 8,
        embed_dim: int = 64,
        mins=None,
        maxs=None,
        wavelength_min: float = 400.0,
        wavelength_max: float = 2500.0,
        wavelength_count: int = 2101,
        spectral_segments: Optional[Sequence[Tuple[float, float]]] = None,
        use_segmented_prospect: bool = True,
        use_segment_residual: bool = True,
        segment_residual_scale: float = 0.05,
        output_clamp: Optional[Tuple[float, float]] = (0.0, 1.0),
        patch_encoder_type: str = "cnn",
        pooling_type: str = "attention_stats",
        band_encoder_mode: str = "shared",
        norm_type: str = "group",
        mlp_hidden_dims: Sequence[int] = (256, 128, 64),
    ):
        super().__init__()

        if bands is None:
            bands = DEFAULT_BANDS
        self.bands = list(bands)

        self.wavelength_min = float(wavelength_min)
        self.wavelength_max = float(wavelength_max)
        self.wavelength_count = int(wavelength_count)
        self.use_segmented_prospect = bool(use_segmented_prospect)
        self.use_segment_residual = bool(use_segment_residual)
        self.segment_residual_scale = float(segment_residual_scale)
        self.output_clamp = output_clamp
        self.embed_dim = int(embed_dim)

        wavelengths_np = make_wavelengths_from_values(
            self.wavelength_min,
            self.wavelength_max,
            self.wavelength_count,
        )
        self.register_buffer(
            "wavelengths",
            torch.as_tensor(wavelengths_np, dtype=torch.float32),
            persistent=False,
        )

        if self.use_segmented_prospect:
            if spectral_segments is None:
                spectral_segments = DEFAULT_SPECTRAL_SEGMENTS
        else:
            spectral_segments = [(self.wavelength_min, self.wavelength_max)]

        self.spectral_segments = normalize_segments(
            spectral_segments,
            self.wavelength_min,
            self.wavelength_max,
        )
        self.num_segments = len(self.spectral_segments)

        idx_np = spectral_segment_indices(wavelengths_np, self.spectral_segments)
        self._segment_buffer_names: List[str] = []
        for i, idx in enumerate(idx_np):
            name = f"_segment_idx_{i}"
            self.register_buffer(
                name,
                torch.as_tensor(idx, dtype=torch.long),
                persistent=False,
            )
            self._segment_buffer_names.append(name)

        boundaries = boundary_indices_from_segments(wavelengths_np, self.spectral_segments)
        self.register_buffer(
            "boundary_indices",
            torch.as_tensor(boundaries, dtype=torch.long),
            persistent=False,
        )

        # Encoders: shared or one encoder per image band.
        band_encoder_mode = str(band_encoder_mode).lower()
        self.band_encoder_mode = band_encoder_mode

        if band_encoder_mode == "shared":
            self.patch_encoder = build_patch_encoder(
                encoder_type=patch_encoder_type,
                in_channels=1,
                base_features=base_features,
                embed_dim=embed_dim,
                norm_type=norm_type,
            )
            self.patch_encoders = None
        elif band_encoder_mode in ["separate", "per_band", "independent"]:
            self.patch_encoder = None
            self.patch_encoders = nn.ModuleDict(
                {
                    b: build_patch_encoder(
                        encoder_type=patch_encoder_type,
                        in_channels=1,
                        base_features=base_features,
                        embed_dim=embed_dim,
                        norm_type=norm_type,
                    )
                    for b in self.bands
                }
            )
        else:
            raise ValueError(
                f"Unknown band_encoder_mode={band_encoder_mode}. "
                "Expected 'shared' or 'separate'."
            )

        self.pool = nn.ModuleDict({b: build_pool(pooling_type, embed_dim) for b in self.bands})

        fused_dim = embed_dim * len(self.bands)

        mlp_layers: List[nn.Module] = []
        in_dim = fused_dim
        for h in mlp_hidden_dims:
            mlp_layers.extend(
                [
                    nn.Linear(in_dim, int(h)),
                    nn.LayerNorm(int(h)),
                    nn.ReLU(inplace=True),
                ]
            )
            in_dim = int(h)

        # One 7-parameter vector per segment in segmented mode.
        mlp_layers.append(nn.Linear(in_dim, self.num_segments * 7))
        self.param_mlp = nn.Sequential(*mlp_layers)

        self.residual_mlp: Optional[nn.Module]
        if self.use_segment_residual:
            self.residual_mlp = nn.Sequential(
                nn.Linear(fused_dim, max(128, embed_dim * 2)),
                nn.LayerNorm(max(128, embed_dim * 2)),
                nn.ReLU(inplace=True),
                nn.Linear(max(128, embed_dim * 2), self.wavelength_count),
                nn.Tanh(),
            )
        else:
            self.residual_mlp = None

        self.physics = PhysicsInformedProspectHead(mins=mins, maxs=maxs)

    def segment_indices(self) -> List[torch.Tensor]:
        return [getattr(self, name) for name in self._segment_buffer_names]

    def _encoder_for_band(self, band_name: str) -> nn.Module:
        if self.band_encoder_mode == "shared":
            assert self.patch_encoder is not None
            return self.patch_encoder
        assert self.patch_encoders is not None
        return self.patch_encoders[band_name]

    def _encode_single_sample(self, band_patches: Dict[str, torch.Tensor]) -> torch.Tensor:
        """Return fused descriptor [1, fused_dim] for one sample."""
        vecs = []
        for b in self.bands:
            P = band_patches[b]
            E = self._encoder_for_band(b)(P)
            v = self.pool[b](E)
            vecs.append(v)
        fused = torch.cat(vecs, dim=0).unsqueeze(0)
        return fused

    def _encode_batch_list(self, batch_band_dict: Dict[str, List[torch.Tensor]]) -> torch.Tensor:
        """
        Efficiently encode a collated batch where each band maps to a list of
        variable-length patch tensors.

        Returns:
            fused descriptors [B, len(bands) * embed_dim]
        """
        B = len(batch_band_dict[self.bands[0]])
        band_descriptors: List[torch.Tensor] = []

        for b in self.bands:
            patch_list = batch_band_dict[b]
            lengths = [int(p.shape[0]) for p in patch_list]

            if sum(lengths) == 0:
                device = next(self.parameters()).device
                dtype = next(self.parameters()).dtype
                pooled = torch.zeros(B, self.embed_dim, device=device, dtype=dtype)
                band_descriptors.append(pooled)
                continue

            all_patches = torch.cat(patch_list, dim=0)
            all_embeddings = self._encoder_for_band(b)(all_patches)
            split_embeddings = torch.split(all_embeddings, lengths, dim=0)

            pooled_list = [self.pool[b](E_i) for E_i in split_embeddings]
            band_descriptors.append(torch.stack(pooled_list, dim=0))

        return torch.cat(band_descriptors, dim=1)

    def _assemble_segmented_spectrum(
        self,
        prospect_full: torch.Tensor,
    ) -> torch.Tensor:
        """
        Assemble final [B,L] spectrum from full PROSPECT curves per segment.

        prospect_full:
            [B, S, L]
        """
        if prospect_full.dim() != 3:
            raise ValueError(f"Expected prospect_full [B,S,L], got {prospect_full.shape}")

        pieces = []
        for i, idx in enumerate(self.segment_indices()):
            idx = idx.to(prospect_full.device)
            pieces.append(prospect_full[:, i, idx])

        return torch.cat(pieces, dim=1)

    def forward_from_fused(self, fused: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Convert fused patch descriptors to spectrum and PROSPECT parameters.

        Args:
            fused: Tensor [B, fused_dim]

        Returns:
            y_fake:
                Tensor [B, L]

            p_params:
                Tensor [B, 7] in full mode
                Tensor [B, S, 7] in segmented mode
        """
        B = fused.shape[0]
        raw_params = self.param_mlp(fused).view(B, self.num_segments, 7)

        raw_flat = raw_params.reshape(B * self.num_segments, 7)
        prospect_flat, p_flat = self.physics(raw_flat)

        # pyPro4Sail returns 2101 values for 400-2500 nm in the usual case.
        if prospect_flat.shape[1] != self.wavelength_count:
            raise RuntimeError(
                f"PROSPECT returned length {prospect_flat.shape[1]}, but "
                f"wavelength_count={self.wavelength_count}. Check wavelength grid."
            )

        prospect_full = prospect_flat.view(B, self.num_segments, self.wavelength_count)
        p_params = p_flat.view(B, self.num_segments, 7)

        y_fake = self._assemble_segmented_spectrum(prospect_full)

        if self.residual_mlp is not None:
            residual = self.segment_residual_scale * self.residual_mlp(fused)
            if residual.shape[1] != y_fake.shape[1]:
                raise RuntimeError(
                    f"Residual length {residual.shape[1]} does not match y_fake "
                    f"length {y_fake.shape[1]}."
                )
            y_fake = y_fake + residual

        if self.output_clamp is not None:
            lo, hi = self.output_clamp
            y_fake = torch.clamp(y_fake, float(lo), float(hi))

        if not self.use_segmented_prospect and p_params.shape[1] == 1:
            p_params = p_params[:, 0, :]

        return y_fake, p_params

    def segment_boundary_loss(self, y: torch.Tensor, reduction: str = "mean") -> torch.Tensor:
        """
        Penalize discontinuities at spectral segment boundaries.

        Args:
            y: spectrum [B,L] or [L]
        """
        if self.boundary_indices.numel() == 0:
            return torch.zeros((), device=y.device, dtype=y.dtype)

        if y.dim() == 1:
            y = y.unsqueeze(0)

        losses = []
        for idx in self.boundary_indices.to(y.device):
            i = int(idx.item())
            if i <= 0 or i >= y.shape[1]:
                continue
            jump = y[:, i] - y[:, i - 1]
            losses.append(jump.pow(2))

        if len(losses) == 0:
            return torch.zeros((), device=y.device, dtype=y.dtype)

        out = torch.stack(losses, dim=1)
        if reduction == "mean":
            return out.mean()
        if reduction == "sum":
            return out.sum()
        return out

    def forward(self, band_patches: Dict[str, torch.Tensor]) -> Tuple[torch.Tensor, torch.Tensor]:
        fused = self._encode_single_sample(band_patches)
        y_fake, p_params = self.forward_from_fused(fused)

        y_fake = y_fake.squeeze(0)
        if p_params.dim() == 3:
            p_params = p_params.squeeze(0)
        else:
            p_params = p_params.squeeze(0)

        return y_fake, p_params

    def forward_batch_list(
        self,
        batch_band_dict: Dict[str, List[torch.Tensor]],
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        fused = self._encode_batch_list(batch_band_dict)
        return self.forward_from_fused(fused)


# ============================================================
# Checking code
# ============================================================


def _make_fake_sample(device):
    return {
        "blue": torch.randn(7, 1, 32, 32, device=device),
        "green": torch.randn(3, 1, 32, 32, device=device),
        "red": torch.randn(5, 1, 32, 32, device=device),
        "nir": torch.randn(9, 1, 32, 32, device=device),
        "red_edge": torch.randn(4, 1, 32, 32, device=device),
    }


def _make_fake_batch(device, B=2):
    batch = {b: [] for b in DEFAULT_BANDS}
    for _ in range(B):
        s = _make_fake_sample(device)
        for b in batch.keys():
            batch[b].append(s[b])
    return batch


def check_generator(gen, device):
    gen.to(device)
    gen.train()

    sample = _make_fake_sample(device)
    y_fake, p_params = gen(sample)

    print("Single forward OK")
    print("  y_fake shape:", tuple(y_fake.shape))
    print("  p_params shape:", tuple(p_params.shape))

    batch = _make_fake_batch(device, B=2)
    y_b, p_b = gen.forward_batch_list(batch)

    print("Batch forward OK")
    print("  y_b shape:", tuple(y_b.shape))
    print("  p_b shape:", tuple(p_b.shape))

    y_true = torch.rand_like(y_b)
    loss = F.l1_loss(y_b, y_true) + 0.1 * gen.segment_boundary_loss(y_b)

    gen.zero_grad(set_to_none=True)
    loss.backward()

    has_grad = False
    max_grad = 0.0
    for _, p in gen.named_parameters():
        if p.grad is not None:
            has_grad = True
            max_grad = max(max_grad, float(p.grad.abs().max().detach().cpu()))

    print("Backward OK")
    print("  has_grad:", has_grad)
    print("  max_grad:", max_grad)


if __name__ == "__main__":
    device = torch.device("cpu")

    gen = MultiSpectralPatchToProspectGenerator(
        bands=DEFAULT_BANDS,
        base_features=8,
        embed_dim=64,
        wavelength_min=400.0,
        wavelength_max=2500.0,
        wavelength_count=2101,
        spectral_segments=DEFAULT_SPECTRAL_SEGMENTS,
        use_segmented_prospect=True,
        use_segment_residual=True,
        segment_residual_scale=0.05,
        patch_encoder_type="cnn",
        pooling_type="attention_stats",
        band_encoder_mode="shared",
        norm_type="group",
    )

    check_generator(gen, device)
